### ISSUE TITLE
Shared drive support

### ISSUE THREAD

**Issue by rsoorajs** [pawanpaudel93/Torrent2GDrive#11]
Can you add shared drive uploading support for your code ?

**Comment by telegrambotdev** [comment]
do you added ream drive support ?

**Comment by askfriends** [comment]
+1

**Comment by pawanpaudel93** [comment]
@askfriends @telegrambotdev I could bring the shared drive support too but the shared drive support requires scope which requires OAuth Consent screen verification.

**Comment by askfriends** [comment]
> @askfriends @telegrambotdev I could bring the shared drive support too but the shared drive support requires scope which requires OAuth Consent screen verification.

there are already many projects similar to this one available, you can take help from them.

**Comment by pawanpaudel93** [comment]
@askfriends @telegrambotdev Shared drive support has been added,

**Comment by askfriends** [comment]
> @askfriends @telegrambotdev Shared drive support has been added,

thanks for the update but we cant deploy it in heroku right?

**Comment by pawanpaudel93** [comment]
@askfriends yes can't deploy to Heroku currently. I haven't found a way to do that as Heroku doesn't let to upload to google drive or to any other (so the account was suspended I guess).
