### ISSUE TITLE
does it use aria2?

### ISSUE THREAD

**Issue by askfriends** [pawanpaudel93/Torrent2GDrive#14]
hi..
thanks for this awesome project..

i want to know what does it use to download and transfer to gdrive?
can we change peer-id and user-agent values?

**Comment by pawanpaudel93** [comment]
@askfriends For download it uses https://github.com/webtorrent/webtorrent and for uploading to google drive it uses googleapis.

**Comment by askfriends** [comment]
> @askfriends For download it uses https://github.com/webtorrent/webtorrent and for uploading to google drive it uses googleapis.

i see..do you know how to change user agent and peer id values in web torrent?

**Comment by pawanpaudel93** [comment]
@askfriends I have no idea for the useragent but peer id seems changeable. Check docs https://webtorrent.io/docs
![image](https://user-images.githubusercontent.com/11836100/108520119-6958a000-72f2-11eb-96ed-d82a51396ff8.png)
