### ISSUE TITLE
Hey Can You Help Me Please Deploying To Heroku

### ISSUE THREAD

**Issue by saulg00dmen** [pawanpaudel93/Torrent2GDrive#9]
Earlier it was working on heroku but now its not working anymore can u look into the logs and tell me if, i am doing something wrong or heroku has banned the app

----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  >= 4.0.0
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version >= 4.0.0...
       Downloading and installing node 14.1.0...
       Using default npm version: 6.14.4
       
-----> Installing dependencies
       Installing node modules (package.json + package-lock)
       up to date in 0.56s
       found 0 vulnerabilities
       
       
-----> Build
       Detected both "build" and "heroku-postbuild" scripts
       Running heroku-postbuild
       
       > Torrent2Drive@1.0.0 heroku-postbuild /tmp/build_2946b26beee410cc9345a565ab179014
       > npm run build-client && npm run install-server
       
       
       > Torrent2Drive@1.0.0 build-client /tmp/build_2946b26beee410cc9345a565ab179014
       > cd ./Torrent2Drive_frontend && npm install && npm run build
       
       
       > core-js@2.6.11 postinstall /tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_frontend/node_modules/babel-runtime/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > core-js@3.6.5 postinstall /tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_frontend/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > ejs@2.7.4 postinstall /tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_frontend/node_modules/ejs
       > node ./postinstall.js
       
       added 1292 packages from 888 contributors and audited 25651 packages in 40.848s
       
       40 packages are looking for funding
         run `npm fund` for details
       
       found 1 low severity vulnerability
         run `npm audit fix` to fix them, or `npm audit` for details
       
       > Torrent2Drive_frontend@1.0.0 build /tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_frontend
       > vue-cli-service build
       
       
-  Building for production...
        DONE  Compiled successfully in 10607ms4:31:37 PM
       
         File                                      Size             Gzipped
       
         dist/js/chunk-vendors.b7ac246e.js         182.67 KiB       61.43 KiB
         dist/js/app.77468d49.js                   13.36 KiB        4.48 KiB
         dist/service-worker.js                    1.05 KiB         0.62 KiB
         dist/precache-manifest.4511edeb77f2557    0.68 KiB         0.33 KiB
         dd44cfc745dbdf18c.js
         dist/css/app.a867a73b.css                 2.50 KiB         0.73 KiB
       
         Images and other types of assets omitted.
       
        DONE  Build complete. The dist directory is ready to be deployed.
        INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
             
       
       > Torrent2Drive@1.0.0 install-server /tmp/build_2946b26beee410cc9345a565ab179014
       > cd ./Torrent2Drive_server && npm install
       
       
       > bufferutil@4.0.1 install /tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_server/node_modules/bufferutil
       > node-gyp-build
       
       
       > utf-8-validate@5.0.2 install /tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_server/node_modules/utf-8-validate
       > node-gyp-build
       
       
       > wrtc@0.4.2 install /tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_server/node_modules/wrtc
       > node scripts/download-prebuilt.js
       
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: bad download
node-pre-gyp ERR! stack     at Unpack.afterTarball (/tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_server/node_modules/node-pre-gyp/lib/install.js:100:46)
node-pre-gyp ERR! stack     at Unpack.emit (events.js:315:20)
node-pre-gyp ERR! stack     at Unpack.[maybeClose] (/tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_server/node_modules/tar/lib/unpack.js:171:12)
node-pre-gyp ERR! stack     at Unpack.[unpend] (/tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_server/node_modules/tar/lib/unpack.js:394:21)
node-pre-gyp ERR! stack     at /tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_server/node_modules/tar/lib/unpack.js:308:46
node-pre-gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:163:23)
node-pre-gyp ERR! System Linux 4.4.0-1062-aws
node-pre-gyp ERR! command "/tmp/build_2946b26beee410cc9345a565ab179014/.heroku/node/bin/node" "/tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_server/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /tmp/build_2946b26beee410cc9345a565ab179014/Torrent2Drive_server/node_modules/wrtc
node-pre-gyp ERR! node -v v14.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
       bad download
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wrtc@0.4.2 install: `node scripts/download-prebuilt.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.KSrHy/_logs/2020-05-03T16_31_52_483Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Torrent2Drive@1.0.0 install-server: `cd ./Torrent2Drive_server && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Torrent2Drive@1.0.0 install-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.KSrHy/_logs/2020-05-03T16_31_52_515Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Torrent2Drive@1.0.0 heroku-postbuild: `npm run build-client && npm run install-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Torrent2Drive@1.0.0 heroku-postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.KSrHy/_logs/2020-05-03T16_31_52_531Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
Build finished

**Comment by Abu3safeer** [comment]
Same error here.

**Comment by pawanpaudel93** [comment]
@Abu3safeer  @saulg00dmen : You can try deploying again. I have fixed it.

**Comment by Abu3safeer** [comment]
Thank you, I will try it now.

**Comment by Abu3safeer** [comment]
Heroku login page is broken, too bad.

**Comment by Abu3safeer** [comment]
After installing it
![image](https://user-images.githubusercontent.com/12091003/88557444-e1980500-d032-11ea-90df-39c5d7991be0.png)

I didn't download anything!

**Comment by pawanpaudel93** [comment]
@Abu3safeer seems Heroku is blocking the Torrent Downloader to GDrive script... I will let you know if the script has been unblocked...

**Comment by Abu3safeer** [comment]
I messaged them for it and this is their replay:
![image](https://user-images.githubusercontent.com/12091003/88656659-56257f00-d0d9-11ea-9056-2e0194e7929b.png)

**Comment by askfriends** [comment]
any update??

**Comment by pawanpaudel93** [comment]
@askfriends no update yet.

**Comment by AhmedNazir** [comment]
I lost my heroku account by using this script

**Comment by askfriends** [comment]
> I lost my heroku account by using this script

its clearly mentioned that w can host it to heroku anymore.
u shudnt have risked ur account.
anyway u can make new one.
